export const socialDetails = [
    { url: "https://facebook.com" },
    { url: "https://instagram.com" },
    { url: "https://twitter.com" },
];

export const footerLinks = [
    { text: "Link 1", url: "#" },
    { text: "Link 2", url: "#" },
    { text: "Link 3", url: "#" },
    { text: "Link 4", url: "#" },
    { text: "Link 5", url: "#" },
];

export const WebDetails = {
    webName: "Studify",
    webMotto: `Stay connected to your child's academic journey with real-time updates. Empower their success with instant access to grades, attendance, and progress.`,
    webMeta: "Generated by create next app",
}

export const SALT_LENGTH = 12;
export const SESSION_AGE = 60 * 60 * 24; // 24 hours